name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]
        include:
          - goos: windows
            goarch: amd64
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -ldflags '-s -w' -o out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Rename for Windows
        if: matrix.goos == 'windows'
        run: mv out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }} out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }}.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Calc hash
        run: |
          cd out
          sha256sum * > sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
          draft: false
